modLoader="javafml"
loaderVersion="[36,)"
license="Public domain"

[[mods]]
modId="waxedwood"
version="1.0"
displayName="Waxed Wood"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/waxed-wood"
#logoFile="logo.png"
#credits=""
authors="StephenBarnes"
description='''
Make wood fireproof using beeswax.'''

[[dependencies.waxedwood]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.waxedwood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
